version: "1"

services:
  app:

    build:
      dockerfile: Dockerfile
      #context: ..
      #target: dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - avito-test-network
  db:
    container_name: postgres
    image: postgres
    restart: always
    command: postgres -c timezone=posix/Asia/Almaty -c log_timezone=posix/Asia/Almaty
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: ${POSTGRES_PGDATA}
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - avito-test-network

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - avito-test-network

networks:
  avito-test-network:
    name: avito-test-network
volumes:
  postgres:
